package bramble

import (
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

var _ entc.Extension = (*entExtension)(nil)

var BrambleConnectionSuffix = "BrambleConnection"

type entExtension struct {
	entc.DefaultExtension
}

func (entExtension) Name() string {
	return `BrambleExtension`
}

func (*entExtension) Templates() []*gen.Template {
	return []*gen.Template{
		gen.MustParse(gen.NewTemplate("goentgql_bramble").Parse(`// Code generated by ent. DO NOT EDIT.
{{/* gotype: entgo.io/ent/entc/gen.Graph */}}

{{/* Add the base header for the generated file */}}
{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

{{ range $n := $.Nodes }}
	{{if index $n.Annotations "` + ConnectionAnnotationName + `" }}

type {{$n.Name}}` + BrambleConnectionSuffix + ` struct {
	*{{$n.Name}}Connection
	ID string
}

	{{ end }}


{{ end }}

`)),
	}
}
