package config

type ServiceConfig struct {
	PackageName string
	Header      string

	EntModulePath     string
	GraphQLModulePath string
}

func ServiceDefaultConfig() *ServiceConfig {
	return &ServiceConfig{
		PackageName: `generated`,
		Header:      `// Code generated by https://github.com/dmalykh/goentgql, DO NOT EDIT.`,
	}
}
