package config

type EntConfig struct {
	SchemaPath                  string
	Header                      string
	Target                      string
	GraphQLSchemaOutputDir      string
	GraphQLSchemaOutputFilename string
	Package                     string
}

func EntDefaultConfig() *EntConfig {
	return &EntConfig{
		Header:                      `// Code generated by https://github.com/dmalykh/goentgql, DO NOT EDIT.`,
		SchemaPath:                  `/schema`,
		Target:                      `/gent`,
		GraphQLSchemaOutputDir:      `/schema/`,
		GraphQLSchemaOutputFilename: `ent.generated.graphql`,
		Package:                     `gent`,
	}
}
